import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/app/scss/main.scss'
import { store, persistor } from '@/app/store'
import { Providers } from '@/app/Provider'
import { PersistGate } from 'redux-persist/integration/react'
import Loading from '@/components/Loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    {/* <PersistGate loading={<Loading />} persistor={persistor}> */}
                    {children}
                    {/* </PersistGate> */}
                </Providers>
            </body>
        </html>
    )
}
